// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 disseqt

package filter

import (
	"strings"
	"testing"
)

func TestShouldInclude(t *testing.T) {
	tests := []struct {
		name     string
		path     string
		patterns []string
		want     bool
	}{
		{"nil patterns includes", "src/foo.go", nil, true},
		{"empty patterns includes", "src/foo.go", []string{}, true},
		{"no match includes", "src/foo.go", []string{"*.py"}, true},
		{"basename match excludes", "src/foo.go", []string{"*.go"}, false},
		{"full path match excludes", "vendor/pkg/x.go", []string{"vendor/*"}, false},
		{"vendor deep no match", "vendor/pkg/x.go", []string{"vendor/*"}, false},
		{"exact basename", "path/to/foo.min.js", []string{"*.min.js"}, false},
		{"malformed pattern is non-match", "foo.go", []string{"[abc"}, true},
		{"one of many matches", "gen.pb.go", []string{"*.py", "*.pb.go"}, false},
		{"vendor deep matches with fnmatch star", "vendor/pkg/x.go", []string{"vendor/*"}, false},
		{"question mark single char", "a.go", []string{"?.go"}, false},
		{"question mark not multi", "ab.go", []string{"?.go"}, true},
		{"char class match", "a.go", []string{"[ab].go"}, false},
		{"char class no match", "c.go", []string{"[ab].go"}, true},
		{"negated char class match", "c.go", []string{"[!ab].go"}, false},
		{"negated char class no match", "a.go", []string{"[!ab].go"}, true},
		{"unterminated bracket is literal", "[foo", []string{"[foo"}, false},
		{"cache hit (same pattern twice)", "b.go", []string{"[ab].go"}, false},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := ShouldInclude(tc.path, tc.patterns); got != tc.want {
				t.Fatalf("ShouldInclude(%q, %v) = %v; want %v", tc.path, tc.patterns, got, tc.want)
			}
		})
	}
}

func TestIsGenerated(t *testing.T) {
	tests := []struct {
		name    string
		path    string
		content string
		want    bool
	}{
		{"empty content", "foo.go", "", false},
		{"plain content", "foo.go", "package foo\nfunc Bar() {}\n", false},
		{"do not edit upper", "foo.go", "// DO NOT EDIT\npackage foo\n", true},
		{"do not edit mixed case", "foo.go", "// Do Not Edit — this file\n", true},
		{"auto-generated", "foo.go", "/* AUTO-GENERATED */\n", true},
		{"autogenerated", "foo.go", "// autogenerated by protoc\n", true},
		{"generated by", "foo.go", "// Generated by tool xyz\n", true},
		{"@generated", "foo.js", "// @generated\nconst x = 1;\n", true},
		{"this file is generated", "foo.go", "// This file is generated. Do not touch.\n", true},
		{"marker beyond scan window", "foo.go", strings.Repeat("x", generatedScanBytes+10) + "\n// DO NOT EDIT\n", false},
		{"marker at end of window", "foo.go", strings.Repeat("x", generatedScanBytes-20) + "\nDO NOT EDIT", true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := IsGenerated(tc.path, tc.content); got != tc.want {
				t.Fatalf("IsGenerated(%q, ...) = %v; want %v", tc.path, got, tc.want)
			}
		})
	}
}
