// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 disseqt
//
// Semantics ported from miracodeai/mira src/mira/core/file_filter.py under Apache License 2.0.

// Package filter implements the file-side filter for diff review:
// exclude-pattern matching and generated-file detection.
package filter

import (
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
)

// generatedMarkers are case-insensitive substrings that mark a file as
// machine-generated when they appear near the top of its content.
var generatedMarkers = []string{
	"DO NOT EDIT",
	"AUTO-GENERATED",
	"AUTOGENERATED",
	"GENERATED BY",
	"AUTOMATICALLY GENERATED",
	"THIS FILE IS GENERATED",
	"@GENERATED",
}

// generatedScanBytes is how many leading bytes of content to scan for
// generated-file markers. Mirrors the Python version's 500-char/first-two-hunks
// window: 1000 bytes is a generous upper bound for a full-file input.
const generatedScanBytes = 1000

// ShouldInclude reports whether a file at path should be included in a review,
// based on excludePatterns (fnmatch-style globs, matched against both the full
// path and the basename).
//
// An empty or nil excludePatterns slice includes everything.
func ShouldInclude(p string, excludePatterns []string) bool {
	if len(excludePatterns) == 0 {
		return true
	}
	base := path.Base(p)
	// Also try filepath.Base for OS-native separators on Windows.
	baseNative := filepath.Base(p)
	for _, pat := range excludePatterns {
		if matchesGlob(pat, p) || matchesGlob(pat, base) || matchesGlob(pat, baseNative) {
			return false
		}
	}
	return true
}

// IsGenerated reports whether the file at path with the given content looks
// machine-generated. The path argument is accepted for future heuristics
// (e.g., ".pb.go" suffix) but the current implementation is content-only,
// matching the Python source.
func IsGenerated(_ string, content string) bool {
	if content == "" {
		return false
	}
	head := content
	if len(head) > generatedScanBytes {
		head = head[:generatedScanBytes]
	}
	upper := strings.ToUpper(head)
	for _, m := range generatedMarkers {
		if strings.Contains(upper, m) {
			return true
		}
	}
	return false
}

// matchesGlob mirrors Python's fnmatch.fnmatch semantics: `*` matches any
// run of characters (including path separators), `?` matches one character,
// and `[set]` is a character class. Unlike filepath.Match, `*` here crosses
// `/`, which is what the Python source relied on for patterns like
// `vendor/*`.
//
// Malformed patterns yield a non-match rather than a hard error, matching
// Python's fnmatch behavior.
func matchesGlob(pattern, name string) bool {
	re, err := globToRegexp(pattern)
	if err != nil {
		return false
	}
	return re.MatchString(name)
}

var globCache sync.Map // map[string]*regexp.Regexp

// globToRegexp translates a Python-style fnmatch pattern to an anchored
// regular expression. Compiled patterns are cached.
func globToRegexp(pattern string) (*regexp.Regexp, error) {
	if v, ok := globCache.Load(pattern); ok {
		return v.(*regexp.Regexp), nil
	}
	var b strings.Builder
	b.WriteByte('^')
	i := 0
	for i < len(pattern) {
		c := pattern[i]
		switch c {
		case '*':
			b.WriteString(".*")
		case '?':
			b.WriteByte('.')
		case '[':
			// Character class: copy until matching `]`. Support the `!`
			// negation prefix by rewriting it to `^`.
			j := i + 1
			if j < len(pattern) && pattern[j] == '!' {
				j++
			}
			if j < len(pattern) && pattern[j] == ']' {
				j++
			}
			for j < len(pattern) && pattern[j] != ']' {
				j++
			}
			if j >= len(pattern) {
				// Unterminated class: literal `[`.
				b.WriteString(regexp.QuoteMeta("["))
			} else {
				class := pattern[i+1 : j]
				if strings.HasPrefix(class, "!") {
					class = "^" + class[1:]
				}
				b.WriteByte('[')
				b.WriteString(class)
				b.WriteByte(']')
				i = j
			}
		default:
			b.WriteString(regexp.QuoteMeta(string(c)))
		}
		i++
	}
	b.WriteByte('$')
	re, err := regexp.Compile(b.String())
	if err != nil {
		return nil, err
	}
	globCache.Store(pattern, re)
	return re, nil
}
