// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 alibaba/open-code-review Contributors

package model

// LlmComment represents a code review comment generated by the LLM.
type LlmComment struct {
	Path           string `json:"path"`
	Content        string `json:"content"`
	SuggestionCode string `json:"suggestion_code,omitempty"`
	ExistingCode   string `json:"existing_code,omitempty"`
	StartLine      int    `json:"start_line"`
	EndLine        int    `json:"end_line"`
	Thinking       string `json:"thinking,omitempty"`
	// Category classifies the finding. One of:
	// bug, security, performance, maintainability, test, style, documentation, other.
	Category string `json:"category,omitempty"`
	// Severity indicates the importance of the finding. One of:
	// critical, high, medium, low.
	Severity string `json:"severity,omitempty"`
	// Source names the producer of the finding. Empty (or "llm") means the
	// main-task LLM. Deterministic scanners tag themselves as
	// "scanner:<tool>", e.g. "scanner:gitleaks". Downstream consumers
	// (Phase 16 scoring, Phase 17 SARIF routing) key on this prefix.
	Source string `json:"source,omitempty"`
}

// CodeReviewResult holds raw LLM-generated review suggestion for a code segment.
type CodeReviewResult struct {
	RelevantFile      string `json:"relevant_file"`
	SuggestionContent string `json:"suggestion_content"`
	ExistingCode      string `json:"existing_code"`
	SuggestionCode    string `json:"suggestion_code"`
}

// ChangeGroup is one bucket in a Summary's change_groups list — a cluster of
// related files with a shared title and one-paragraph rationale.
type ChangeGroup struct {
	Title   string   `json:"title"`
	Files   []string `json:"files"`
	Summary string   `json:"summary"`
}

// Summary is the cheap-tier summarizer's structured output. All fields are
// optional and empty on any parse / call failure — Phase 17 consumes this for
// the PR description block, so the emitter must tolerate blanks.
type Summary struct {
	Walkthrough  string        `json:"walkthrough,omitempty"`
	ChangeGroups []ChangeGroup `json:"change_groups,omitempty"`
	TestingNotes string        `json:"testing_notes,omitempty"`
	Risk         string        `json:"risk,omitempty"`
}

// Labels is the cheap-tier labeler's structured output.
type Labels struct {
	PRType         string   `json:"pr_type,omitempty"`
	Domains        []string `json:"domains,omitempty"`
	RiskTag        string   `json:"risk_tag,omitempty"`
	OwnershipHints []string `json:"ownership_hints,omitempty"`
}
